import React from "react";
import { useRouter } from 'next/router';
import Head from "next/head";
import Navbar from "../../Components/navbar";
import Footer from "../../Components/footer";

const ProjectPage = () => {
    const idString = useRouter().query.id as string;
    const [pageHeader, setPageHeader] = React.useState('');
    const [pageContent, setPageContent] = React.useState('');
    
    return (
      <>
        <Head>
          <title>Bee's Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar without={idString} />
          <main>

          </main>
        <Footer />
      </>
    );
  }

export default ProjectPage;

