import Head from "next/head";
import Navbar from "../Components/navbar";
import Footer from "../Components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bee's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main
        className="bg-purple-200"
        style={{ minHeight: "calc(100vh - 4rem)" }}
      ></main>
      <Footer />
    </>
  );
}
