import React from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Navbar from "../../Components/navbar";
import Footer from "../../Components/footer";

const ProjectPage = () => {
  const idString = useRouter().query.id as string;
  const [pageHeader, setPageHeader] = React.useState("");
  const [pageContent, setPageContent] = React.useState("");
  const [pageImage, setPageImage] = React.useState("");
  const [githubLink, setGithubLink] = React.useState("");
  const [deployedLink, setDeployedLink] = React.useState("");

  React.useEffect(() => {
    fetch("/projects.json")
      .then((response) => response.json())
      .then((data) => {
        const project = data.find(
          (item: { name: string }) => item.name === idString
        );
        if (project) {
          setPageHeader(project.name);
          setPageContent(project.pageContent);
          setPageImage(project.image);
          setGithubLink(project.githubLink);
          setDeployedLink(project.deployedLink);
        } else {
          return
        }
      });
  }, [idString]);
  

  return (
    <>
      <Head>
        <title>Bee's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar without={idString} />
      <main className="flex flex-col items-center justify-center">
        <h1 className="text-5xl font-bold">{pageHeader}</h1>
        <div className="w-1/4 p-6">
          <img
            className="w-full h-full object-cover"
            src={pageImage}
            alt={pageHeader}
          />
        </div>
        <p className="p-6">{pageContent}</p>
        <div className="flex flex-row justify-center w-1/2 h-1/4">
          <div className="flex flex-col items-center justify-center w-1/2 h-full">
            {githubLink ? <h4>Github Link:</h4> : <h4></h4>}
            <a href={githubLink}>{githubLink}</a>
          </div>
          <div className="flex flex-col items-center justify-center w-1/2 h-full">
            {deployedLink ? <h4>Deployed Link:</h4> : <h4></h4>}
            <a href={deployedLink}>{deployedLink}</a>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default ProjectPage;
